"""Generate standards-compliant advanced storage test runs."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

from qulab.storage import OptionalDependencyError, ZarrBackend, create_synthetic_advanced_run


CSV_CASES = [
    ("synthetic_csv_1d_scalar", {"mw_freq_hz": 7}, False, False),
    ("synthetic_csv_2d_scalar", {"mw_freq_hz": 5, "tau_s": 4}, False, False),
    ("synthetic_csv_3d_scalar", {"mw_freq_hz": 4, "tau_s": 3, "field_v": 2}, False, False),
    ("synthetic_csv_point_trace", {"mw_freq_hz": 4, "tau_s": 3, "time_s": 12}, True, False),
    ("synthetic_csv_multichannel_trace", {"mw_freq_hz": 3, "tau_s": 2, "time_s": 10, "channel": 2}, True, True),
]

ZARR_CASES = [
    ("synthetic_zarr_2d_scalar", {"mw_freq_hz": 5, "tau_s": 4}, True, False),
    ("synthetic_zarr_point_trace", {"mw_freq_hz": 4, "tau_s": 3, "time_s": 12}, True, False),
    ("synthetic_zarr_multichannel_trace", {"mw_freq_hz": 3, "tau_s": 2, "time_s": 10, "channel": 2}, True, True),
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="runs/advanced_test_data", help="Directory that will contain one generated batch")
    parser.add_argument("--batch-name", default=None, help="Batch directory name. Defaults to a timestamp.")
    parser.add_argument("--include-zarr", action="store_true", help="Generate optional Zarr runs when zarr is installed")
    args = parser.parse_args(argv)

    batch_name = args.batch_name or datetime.now().strftime("%Y%m%d_%H%M%S")
    batch_root = _unique_path(Path(args.root) / batch_name)
    batch_root.mkdir(parents=True)

    generated: list[Path] = []
    for run_id, dims, include_trace, multichannel in CSV_CASES:
        generated.append(
            create_synthetic_advanced_run(
                batch_root,
                dims=dims,
                include_trace=include_trace,
                backend="csv",
                multichannel=multichannel,
                run_id=run_id,
            )
        )

    zarr_status = "not requested"
    if args.include_zarr:
        if ZarrBackend.available():
            zarr_status = "generated"
            for run_id, dims, include_trace, multichannel in ZARR_CASES:
                generated.append(
                    create_synthetic_advanced_run(
                        batch_root,
                        dims=dims,
                        include_trace=include_trace,
                        backend="zarr",
                        multichannel=multichannel,
                        run_id=run_id,
                    )
                )
        else:
            zarr_status = "skipped because optional package 'zarr' is unavailable"

    _write_batch_readme(batch_root, generated, zarr_status)
    print(batch_root)
    for path in generated:
        print(path)
    if args.include_zarr and zarr_status.startswith("skipped"):
        print(zarr_status)
    return 0


def _unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    index = 1
    while True:
        candidate = path.with_name(f"{path.name}_{index:02d}")
        if not candidate.exists():
            return candidate
        index += 1


def _write_batch_readme(batch_root: Path, generated: list[Path], zarr_status: str) -> None:
    lines = [
        "# Qulab Advanced Storage Test Data",
        "",
        "This batch was generated by `qulab.scripts.generate_advanced_test_data`.",
        "",
        "CSV runs are mandatory and use `dataset_manifest.json` plus `tables/`.",
        f"Zarr status: {zarr_status}.",
        "",
        "Runs:",
    ]
    lines.extend(f"- `{path.name}`" for path in generated)
    lines.extend(
        [
            "",
            "Useful commands:",
            "",
            "```bash",
            "PYTHONPATH=src python -m qulab.viewer.pyqt_viewer_app <run_path> csv",
            "PYTHONPATH=src python -m pytest tests/unit/test_dataset_slicing.py tests/unit/test_run_reader.py",
            "```",
            "",
        ]
    )
    batch_root.joinpath("README.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
